export default {
    "1C" : "oneC (1c)",
    "ABNF" : "abnf",
    "ActionScript" : "actionscript",
    "Ada" : "ada",
    "AngelScript" : "angelscript",
    "Apache" : "apache",
    "AppleScript" : "applescript",
    "Arcade" : "arcade",
    "Arduino" : "arduino",
    "Armasm" : "armasm",
    "AsciiDoc" : "asciidoc",
    "AspectJ" : "aspectj",
    "AutoHotkey" : "autohotkey",
    "Autoit" : "autoit",
    "AVR Assembler " : "avrasm",
    "AWK" : "awk",
    "Axapta" : "axapta",
    "Bash" : "bash",
    "Basic" : "basic",
    "BNF" : "bnf",
    "BrainF" : "brainfuck",
    "C" : "c",
    "C++" : "cpp",
    "C#" : "csharp",
    "CoffeeScript" : "coffeescript",
    "Crystal" : "crystal",
    "CSS" : "css",
    "D" : "d",
    "Dart" : "dart",
    "Django" : "django",
    "F#" : "fsharp",
    "Fortran" : "fortran",
    "G-Code" : "gcode",
    "Go" : "go",
    "Haml" : "haml",
    "Haskell" : "haskell",
    "HTML" : "html",
    "Java" : "java",
    "JavaScript (JS)" : "javascript",
    "JSON" : "json",
    "Kotlin" : "kotlin",
    "PHP" : "php",
    "Python" : "python",
    "SQL" : "sql",
    "Swift" : "swift",
    "TypeScript (TS)" : "typescript",
    "Visual Basic .NET (VB.NET)" : "vbnet",
    "Visual Basic Script (VBScript)" : "vbscript",
    "YAML" : "yaml"
}

//     "cal",
//     "capnproto",
//     "ceylon",
//     "clean",
//     "clojureRepl (clojure-repl)",
//     "clojure",
//     "cmake",
//     ,
//     "coq",
//     "cos",
//     "crmsh",
//     "",
//     "csp",
//     "delphi",
//     "diff",
//     "dns",
//     "dockerfile",
//     "dos",
//     "dsconfig",
//     "dts",
//     "dust",
//     "ebnf",
//     "elixir",
//     "elm",
//     "erb",
//     "erlangRepl (erlang-repl)",
//     "erlang",
//     "excel",
//     "fix",
//     "flix",
//     "gams",
//     "gauss",
//     "",
//     "gherkin",
//     "glsl",
//     "gml",
//     "golo",
//     "gradle",
//     "groovy",
//     "handlebars",
//     "haxe",
//     "hsp",
//     "htmlbars",
//     "http",
//     "hy",
//     "inform7",
//     "ini",
//     "irpf90",
//     "isbl",
//     "jbossCli (jboss-cli)",
//     "juliaRepl (julia-repl)",
//     "julia",
//     "lasso",
//     "latex",
//     "ldif",
//     "leaf",
//     "less",
//     "lisp",
//     "livecodeserver",
//     "livescript",
//     "llvm",
//     "lsl",
//     "lua",
//     "makefile",
//     "markdown",
//     "mathematica",
//     "matlab",
//     "maxima",
//     "mel",
//     "mercury",
//     "mipsasm",
//     "mizar",
//     "mojolicious",
//     "monkey",
//     "moonscript",
//     "n1ql",
//     "nginx",
//     "nim",
//     "nix",
//     "nodeRepl (node-repl)",
//     "nsis",
//     "objectivec",
//     "ocaml",
//     "openscad",
//     "oxygene",
//     "parser3",
//     "perl",
//     "pf",
//     "pgsql",
//     "phpTemplate (php-template)",
//     "plaintext",
//     "pony",
//     "powershell",
//     "processing",
//     "profile",
//     "prolog",
//     "properties",
//     "protobuf",
//     "puppet",
//     "purebasic",
//     "pythonRepl (python-repl)",
//     "q",
//     "qml",
//     "r",
//     "reasonml",
//     "rib",
//     "roboconf",
//     "routeros",
//     "rsl",
//     "ruby",
//     "ruleslanguage",
//     "rust",
//     "sas",
//     "scala",
//     "scheme",
//     "scilab",
//     "scss",
//     "shell",
//     "smali",
//     "smalltalk",
//     "sml",
//     "sqf",
//     "sqlMore (sql_more)",
//     "stan",
//     "stata",
//     "step21",
//     "stylus",
//     "subunit",
//     "taggerscript",
//     "tap",
//     "tcl",
//     "thrift",
//     "tp",
//     "twig",
//     "vala",
//     "vbscriptHtml (vbscript-html)",
//     "verilog",
//     "vhdl",
//     "vim",
//     "x86asm",
//     "xl",
//     "xml",
//     "xquery",
//     "zephir"
// ]